### ISSUE TITLE
Reported runtime

### ISSUE THREAD

**Issue by david-navarr** [YingqianWang/DistgDisp#3]
Hi! First of all, congratulations for the great work and results. 

I'm testing this net in my own images, and its outputing a really good estimation of disparity, but I cannot replicate the runtimes reported on HCI benchmark (0.004), if I set crop to True, the average runtime of all the process is around 7 secs, while setting crop to False almost doubles this time. I have pytorch 1.7.1 installed on my computer along with cuda 11.0, and the GPU is a NVIDIA GeForce GTX 1070.

Do you know if there's something I might be doing wrong?

Thanks in advance!

**Comment by YingqianWang** [comment]
Hi, 

Thanks for your interst to our work.  A large cuda memory (24 GB) is required to reproduce the running time reported on the HCI 4D benchmark (also in our paper). Consequently, we test our network on an RTX 3090 GPU without performing crop. Moreover, some tensors in our network need to be pre-registered to save the inference time, as we observed that the data transferred from CPU to GPU can result in a significant time cost. We will release the version that can reproduce the running time of our method in the comming future.
