### ISSUE TITLE
The compressed package in the log/file is damaged

### ISSUE THREAD

**Issue by JIAJIAqi-1** [YingqianWang/DistgDisp#4]
Hi! thank you so much for sharing the code！
When I run test.py, I find that I can't decompress your training results in the log file
where did i go wrong?
very much looking forward to your reply

**Comment by YingqianWang** [comment]
I have not met this problem. Before I uploaded the codes and models, I have run both train.py and test.py on my PC and ensure that this project works well. Have other peers met the same problem and can provide help?
